version: "3.9"
services:
  app:
    container_name: red-bici
    restart: always
    build: ./
    ports:
      - "8080:3002"
    links:
      - mongo
    environment:
      - HOST=0.0.0.0
      - PORT=3002
  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"